### ISSUE TITLE
linear superposition of LaserPulse objects error

### ISSUE THREAD

**Issue by ilovekenny** [albeco/LaserPulse#1]
There is a problem with plus and minus function for from an example "linear superposition of LaserPulse objects". As I see in plus.m file you described two functions plus and polarsum. But pulse1 argument is not visible for polarsum function as it is not global variable.

Undefined variable "pulse1" or class "pulse1.unwrapPhase".

Error in LaserPulse/plus>polarsum (line 26)
if pulse1.unwrapPhase 

Error in LaserPulse/binaryOperator (line 81)
    [newTempAmp, newTempPhase] = op( ...

Error in + (line 18)
res = binaryOperator(pulse1, pulse2, @polarsum);

Error in pulse_linear_mixing (line 22)
psum = p1 + p2;

**Comment by albeco** [comment]
Hi,

thank you very much for noticing the bug! and sorry for the late reply: now it should be fixed.

Please let me know when you find other issues.
