### ISSUE TITLE
SPM

### ISSUE THREAD

**Issue by gab-ral** [albeco/LaserPulse#2]
Hi, 
I have been trying to run the SPM example (matlab 2020a) and I came across with the following ?

>> pulse_self_phase_modulation
Unable to use a value of type matlab.graphics.axis.Axes as an
index.

Error in LaserPulse/subsref (line 40)
  efield = subsref(efield, ref(2:end));

Error in pulse_self_phase_modulation (line 32)
p2.plot(ax)

Do you have any suggestions?
Thanks
gab

**Comment by albeco** [comment]
Hi Gab,

thanks for letting me know. There was indeed a bug in subsref.

Now it is fixed and the pulse_self_phase_modulation runs without errors on my matlab (2015a).

Best,
Alberto
