### ISSUE TITLE
pulse_dispersion_scan.m: Too many output arguments error

### ISSUE THREAD

**Issue by cephLpod** [albeco/LaserPulse#3]
When I run the pulse_dispersion_scan.m example in either MATLAB R2016b or R2020b, I get the following errors:

Error using LaserPulse/polynomialPhase
Too many output arguments.

Error in LaserPulse/subsref (line 23)
    efield = pulse.(ref(1).subs);

Error in pulse_dispersion_scan (line 15)
p.polynomialPhase([2000 100 0 0])

I see someone on the Mathworks site is also experiencing a similar issue, and some of the other examples (such as pulse_autocorrelation.m and pulse_chirp_scan.m) give me similar errors.

Thanks for any help you can give with this issue - I can't wait to use your code for some simulations!

**Comment by albeco** [comment]
thanks for letting me know!

there was a bug in the customized subsref operator; I reverted it to the default one and now at least in my matlab2015a the example scripts seem to work.

Please let me know if you find other bugs!

**Comment by cephLpod** [comment]
Thank you!! That’s fixed the problem for me.

**Comment by cephLpod** [comment]
May I also ask a question about usage? Do you happen to have a reference
that talks about how to propagate a pulse through a lens?

Thanks!

**Comment by albeco** [comment]
Hi

- *usage*: I typically used the LaserPulse code as a library for simulations in nonlinear/ultrafast optics, which often involve Fourier transforming forth and back, zero padding, etc..

- *propagation through a lens*: the LaserPulse code currently accounts only for the pulse broadening effect (see the .propagate() method). It is possible to store the wavefront information by initializing the pulse with a multi-dimensional arrays, but there is no dedicated method for it. A very good reference about the propagation/focusing of optical fields is: https://www.photonics.ethz.ch/fileadmin/user_upload/Courses/NanoOptics/focus3.pdf;
